alias xvia_aliases="code ~/.scripts/xvia/aliases.sh"

export XVIA_ROOT="/Volumes/APFS_External_SSD/workspace/xvia"

alias xvia="cd $XVIA_ROOT"
alias xportal="cd $XVIA_ROOT/portal"
alias xcatalog="cd $XVIA_ROOT/xvia-catalog"
alias xadmin="cd $XVIA_ROOT/xvia-services"
alias xdesign="cd $XVIA_ROOT/xvia-design-system"
alias xpainel="cd $XVIA_ROOT/painel-cidadao"
alias xagendfe="cd $XVIA_ROOT/agendamento-servicos"
alias xagendm="cd $XVIA_ROOT/agendamento-middleware"
alias xdetranfe="cd $XVIA_ROOT/detran-front-end"
alias xdetranm="cd $XVIA_ROOT/detran-middleware"
alias xwhatsm="cd $XVIA_ROOT/whatsapp-middleware"
alias xsedepe="cd $XVIA_ROOT/sedepe"
alias xapp="cd $XVIA_ROOT/xvia-mobile-app"
alias xsefazfe="cd $XVIA_ROOT/sefaz-front-end"
alias xsefazm="cd $XVIA_ROOT/sefaz-middleware"
alias xmaem="cd $XVIA_ROOT/colo-de-mae-middleware"
alias xsmartpc="cd $XVIA_ROOT/smartpass-perfil-cidadao"
alias xsmartb="cd $XVIA_ROOT/smartpass-backend"
alias xevagptm="cd $XVIA_ROOT/xvia-middleware-evagpt"

alias code_xvia="code $XVIA_ROOT/xvia.code-workspace"
